### PR TITLE
Chong app patch1 - Improve socket serving and prevent session timeout 

### PR DESCRIPTION
**Pull request by chongy076**
## Description
Using  WSGIServer to run instead of socketio.run to run the app instance, and change 
socketio = SocketIO(app, async_mode='gevent')  to socketio = SocketIO(app, async_mode='gevent', ping_timeout=30, ping_interval=15)

Fixes # (issue)
1. prevent web update while generating from not showing.
2.  weird disconnected on session. 

## Type of change
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
Please put an `x` in the boxes that apply. You can also fill these out after creating the PR.

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have tested this code locally, and it is working as intended
- [X] I have updated the documentation accordingly

## Screenshots
If applicable, add screenshots to help explain your changes.
[add ping to prevent session timeout]
image

[server from WSGIServer instead of socketio]
image

### CODE REVIEW

**Comment by andzejsp** [comment]
@chongy076 can you make this work behind proxy with https TLS/SSL?

**Comment by chongy076** [comment]
> @chongy076 can you make this work behind proxy with https TLS/SSL?

I think can, but here is midnight already.

**Review by ParisNeo — APPROVED** [review]
great!
Next step, making this work over a proxy :)

**Comment by chongy076** [comment]
Hi , 
I am still doing quite a numbers of testing, and still many to go.
But this is how it is look liked when serve in https.

i noticed, the certificate generated is quite sensitive, if the domain url not matched it just rejected by browser (so extra careful on that). there are html and js need to be check as well.

image

the proxy code , I  had added it , but only can test it after done on ssl.

Since I am doing a lot of research and project, my laptop don't have much disk spaces to play around with. So I keep some in here. 

import ssl


app = Flask("GPT4All-WebUI", static_url_path="/static", static_folder="static")

app.config['SSL_REDIRECT'] = True


# Add the proxy middleware chong
#app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_for=1)

# Configure SSL termination
if app.config.get('SSL_REDIRECT', False):
    from flask_sslify import SSLify #pip install flask_sslify
    sslify = SSLify(app)
    # Enable SSL chong
    #context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ssl_context.load_cert_chain('server.crt', 'server.key') 

#[for specific site]
#openssl req -x509 -newkey rsa:4096 -nodes -out server.crt -keyout server.key -days 365 -config #....\AppData\Local\miniconda3\Library\openssl.cnf
#[for localhost]
#openssl req -x509 -newkey rsa:4096 -nodes -out server.crt -keyout server.key -days 365  -config #...\AppData\Local\miniconda3\Library\openssl.cnf -subj /CN=localhost


"""
In Windows, you can install the certificate by following these steps:

Open the Certificate Manager: press Win + R keys to open the Run dialog, type certmgr.msc, and press Enter.

In the Certificate Manager, click on the "Trusted Root Certification Authorities" folder in the left pane.

Click on the "Certificates" folder in the right pane.

Right-click anywhere in the right pane and select "All Tasks" > "Import" from the context menu.

In the Certificate Import Wizard, click "Next".

Click the "Browse" button and locate the cert.pem file that you generated with OpenSSL.

Click "Next".

Select "Place all certificates in the following store" and click "Browse".

Select the "Trusted Root Certification Authorities" folder and click "OK".

Click "Next".

Click "Finish".
"""

# Configure proxy headers
if app.config.get('PROXY_FIX', False):
    from werkzeug.middleware.proxy_fix import ProxyFix # pip install werkzeug
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_port=1)



socketio = SocketIO(app, async_mode='gevent', ping_timeout=30, ping_interval=15)
.....


    # chong Define custom WebSocketHandler with error handling 
    class CustomWebSocketHandler(WebSocketHandler):
        def handle_error(self, environ, start_response, e):
            # Handle the error here
            print("WebSocket error:", e)
            super().handle_error(environ, start_response, e)
    

    # chong -add socket server    
    app.config['debug'] = config["debug"]

    if config["debug"]:
        print("debug mode:true")    
    else:
        print("debug mode:false")

    if app.config.get('SSL_REDIRECT', False):        
        url = f'https://{config["host"]}:{config["port"]}'    
        print(f"Please open your browser and go to {url} to view the ui")
        http_server = WSGIServer((config["host"], config["port"]), app, handler_class=WebSocketHandler, ssl_context=ssl_context)
    else:
        url = f'http://{config["host"]}:{config["port"]}'    
        print(f"Please open your browser and go to {url} to view the ui")
        http_server = WSGIServer((config["host"], config["port"]), app, handler_class=WebSocketHandler)
    http_server.serve_forever()

**Comment by andzejsp** [comment]
im not pythonist, but my question is gonna be straight.
Lets say i host this application on VM, then use reverse proxy manager that manages the local ip:port acces from a speciffic domain name. For example nginx proxy manager. THis manager generates SSL certs for the speciffic domain name.
Do you need to copy these certs to the GPT4ALL-UI repo folder somewhere to use the application from the domain name?

Im no scientist when it comes to these things. 

Lately when the repo moved to websocket, i cant post my prompts no more because of errors:

image

So the idea was for someone to fix the code so that you could deploy this app and make it public, keeping the packets safe.

From what i could understand from the code you posted, you could just set SSL = true, this param could be exported into the config.

If you have working code, i could clone and test this real quick, as i already have VM set up, just need the code :)

**Comment by chongy076** [comment]
> im not pythonist, but my question is gonna be straight. Lets say i host this application on VM, then use reverse proxy manager that manages the local ip:port acces from a speciffic domain name. For example nginx proxy manager. THis manager generates SSL certs for the speciffic domain name. Do you need to copy these certs to the GPT4ALL-UI repo folder somewhere to use the application from the domain name?
> 
> Im no scientist when it comes to these things.
> 
> Lately when the repo moved to websocket, i cant post my prompts no more because of errors:
> 
> image
> 
> So the idea was for someone to fix the code so that you could deploy this app and make it public, keeping the packets safe.
> 
> From what i could understand from the code you posted, you could just set SSL = true, this param could be exported into the config.
> 
> If you have working code, i could clone and test this real quick, as i already have VM set up, just need the code :)
Hi,

I had done some research prior involving in this gpt4all_UI in SSL , email ,certificate and IIS and apache hosting , php, C#,c++,vb.net, smtp , hosting and etc. Although , this area is really tough. I am still learning as much as I can.
seem like this is never ending learning stories. 

Once my end is done on the request, by default it's already using https with cert that you generated for your hosting server.
on top of that you also can add certificate into nginx, see [https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https](url) 

Hope this would help, but if you have input . Do share with us. 

Regards

**Pull request merged**
