### PR TITLE
Run GPT4All-UI on Google colab

### PR DESCRIPTION
**Pull request by MyEcoria**

### CODE REVIEW

**Review by ParisNeo — COMMENTED** [review]
The colab path does not exist

**Comment by MyEcoria** [comment]
It is the ChatGptAll-Ui.ipynb file that must be imported here: https://colab.research.google.com/

**Comment by navyfighter12** [comment]
$ git clone https://github.com/MyEcoria/gpt4all-ui-colab.git myia
Cloning into 'myia'...
remote: Repository not found.
fatal: repository 'https://github.com/MyEcoria/gpt4all-ui-colab.git/' not found
(base)

**Comment by MyEcoria** [comment]
https://github.com/nomic-ai/gpt4all-ui/pull/123

**Pull request merged**
